# Generated by Django 3.1.14 on 2024-10-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_auto_20241007_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='class_registration',
        ),
    ]
