# Generated by Django 3.1.14 on 2024-10-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20241009_0038'),
        ('academic', '0004_remove_learner_class_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Learner',
        ),
    ]
