# Generated by Django 3.1.14 on 2024-10-14 22:14

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_auto_20241009_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], default='10', max_length=2)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('fees_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Mathematics', 'Mathematics'), ('Mathematics Exam', 'Mathematics Examination'), ('Physical Science', 'Physical Science'), ('Physical Science Exam', 'Physical Science Examination')], default='Mathematics', max_length=21)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='classregistration',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='classregistration',
            name='center',
        ),
        migrations.RemoveField(
            model_name='classregistration',
            name='session',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='date',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='session',
            name='day',
            field=models.CharField(choices=[('SAT', 'Saturday'), ('SUN', 'Sunday')], default='SAT', max_length=4),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(choices=[('12:00', '12:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00')], default='16:00'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('12:00', '12:00'), ('14:00', '14:00')], default='10:00'),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set(),
        ),
    ]
