# Generated by Django 3.1.14 on 2024-10-14 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('result', '0002_auto_20241015_0014'),
        ('academic', '0007_auto_20241015_0014'),
        ('attendance', '0004_auto_20241015_0014'),
        ('center_manager', '0003_auto_20241015_0014'),
        ('learner', '0004_auto_20241015_0014'),
        ('teacher', '0004_auto_20241015_0014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Center',
        ),
        migrations.DeleteModel(
            name='ClassRegistration',
        ),
        migrations.AddField(
            model_name='registration',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='center_manager.center'),
        ),
        migrations.AddField(
            model_name='registration',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learner.learner'),
        ),
        migrations.RemoveField(
            model_name='session',
            name='class_info',
        ),
        migrations.AddField(
            model_name='session',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.grade'),
        ),
        migrations.AddField(
            model_name='session',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.subject'),
        ),
        migrations.DeleteModel(
            name='ClassInfo',
        ),
    ]
