# Generated by Django 3.1.14 on 2024-10-14 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_auto_20241015_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
