# Generated by Django 3.1.14 on 2024-10-14 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20241015_0014'),
        ('learner', '0004_auto_20241015_0014'),
        ('address', '0003_auto_20241015_0014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Union',
        ),
        migrations.DeleteModel(
            name='Upazilla',
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.province'),
        ),
    ]
