# Generated by Django 3.1.14 on 2024-10-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20241015_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='province',
            field=models.CharField(choices=[('EC', 'Eastern Cape'), ('GP', 'Gauteng'), ('KZN', 'KwaZulu-Natal'), ('LP', 'Limpopo'), ('MP', 'Mpumalanga'), ('NC', 'Northern Cape'), ('NW', 'North West'), ('WC', 'Western Cape'), ('FS', 'Free State')], max_length=50, null=True, unique=True),
        ),
    ]
