# Generated by Django 5.1.1 on 2024-10-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_type', models.CharField(choices=[('Finance Manager', 'Finance Manager'), ('Centre Manager', 'Centre Manager'), ('Teacher', 'Teacher')], default='Teacher', max_length=50)),
                ('name_surname', models.CharField(default='Name & Surname', max_length=100)),
                ('contact_number', models.CharField(default='062 123 4472', max_length=10)),
                ('email_address', models.EmailField(default='example@gmail.com', max_length=254)),
                ('physical_address', models.TextField(default='No Address')),
                ('documents', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
