# Generated by Django 3.1.14 on 2024-10-16 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_auto_20241015_0111'),
        ('center_manager', '0003_auto_20241015_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centermanager',
            old_name='surnname',
            new_name='surname',
        ),
        migrations.AlterField(
            model_name='center',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centers', to='address.address'),
        ),
        migrations.AlterField(
            model_name='center',
            name='center_manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='center', to='center_manager.centermanager'),
        ),
    ]
