# Generated by Django 3.1.14 on 2024-10-17 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('center_manager', '0004_auto_20241017_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='centermanager',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='center_managers', to='auth.user'),
            preserve_default=False,
        ),
    ]
