# Generated by Django 3.1.14 on 2024-10-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0002_auto_20241009_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicinfo',
            name='previous_academic_info',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='religion',
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=311352, unique=True),
        ),
        migrations.DeleteModel(
            name='PreviousAcademicInfo',
        ),
    ]
