# Generated by Django 3.1.14 on 2024-10-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0005_auto_20241015_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='disabilities',
            field=models.ManyToManyField(blank=True, related_name='learners_with_disabilities', to='learner.Disability'),
        ),
        migrations.AlterField(
            model_name='disability',
            name='learners',
            field=models.ManyToManyField(related_name='learner_disabilities', to='learner.Learner'),
        ),
    ]
