# Generated by Django 3.1.14 on 2024-10-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0006_auto_20241017_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disability',
            name='learners',
        ),
    ]
