# Generated by Django 3.1.14 on 2024-10-17 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0007_remove_disability_learners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='disabilities',
        ),
        migrations.AddField(
            model_name='learner',
            name='disabilities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learner.disability'),
        ),
    ]
