# Generated by Django 3.1.14 on 2024-10-17 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0008_auto_20241017_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='disabilities',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learner.disability'),
        ),
    ]
