# Generated by Django 3.1.14 on 2024-10-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20241015_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerattendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], default='Present', max_length=10),
        ),
    ]
