# Generated by Django 3.1.14 on 2024-10-19 20:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20241018_0151'),
        ('attendance', '0006_auto_20241015_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerattendance',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learnerattendance',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learnerattendance',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learnerattendance',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='learnerattendance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='learnerattendance',
            name='attendance_date',
        ),
        migrations.RemoveField(
            model_name='learnerattendance',
            name='created_at',
        ),
    ]
